import core from "../setup";
import isBoolean from "./isBoolean";
import isDocument from "./isDocument";
import isElement from "./isElement";
import isFunction from "./isFunction";
import isNodetype from "./isNodetype";
import isNull from "./isNull";
import isNumber from "./isNumber";
import isNumeric from "./isNumeric";
import isPlainObject from "./isPlainObject";
import isString from "./isString";
import isTypeof from "./isTypeof";
import isUndefined from "./isUndefined";
import isWindow from "./isWindow";
import isWpopv from "./isWpopv";

core.isBoolean     = isBoolean;
core.isDocument    = isDocument;
core.isElement     = isElement;
core.isFunction    = isFunction;
core.isNodetype    = isNodetype;
core.isNull        = isNull;
core.isNumber      = isNumber;
core.isNumeric     = isNumeric;
core.isPlainObject = isPlainObject;
core.isString      = isString;
core.isTypeof      = isTypeof;
core.isUndefined   = isUndefined;
core.isWindow      = isWindow;
core.isWpopv       = isWpopv;
