export var rquickExpr        = /^(?:#([\w\-]+)|(\w+)|\.([\w\-]+))$/,
		   whitespace        = '[\\x20\\t\\r\\n\\f]',
		   operators         = "([*^$|!~]?=)",
		   rheader           = /h\d/i,
		   characterEncoding = '(?:\\\\.|[-\\w]|[^\\x00-\\xa0])+',
		   identifier        = characterEncoding.replace( 'w', 'w#' ),
		   attributes        = '\\[' + whitespace + '*(' + characterEncoding + ')' + whitespace + '*(?:' + operators + whitespace + '*(?:([\'\"])((?:\\\\.|[^\\\\])*?)\\3|(' + identifier + ')|)|)' + whitespace + '*\\]',
		   pseudos           = ':(' + characterEncoding + ')(?:\\((?:([\'\"])((?:\\\\.|[^\\\\])*?)\\2|([^()[\\]]*|(?:(?:' + attributes + ')|[^:]|\\\\.)*|.*))\\)|)',
		   pos               = ':(even|odd|eq|gt|lt|nth|first|last)(?:\\(' + whitespace + '*((?:-\\d)?\\d*)' + whitespace + '*\\)|)(?=[^-]|$)',
		   rinputs           = /input|select|textarea|button/i,
		   rescape           = /'|\\/g,
		   rsibling          = new RegExp( whitespace + '*[+~]' ),
		   rattribute        = new RegExp( attributes ),
		   rpseudoUpperkeys  = new RegExp( ':.*[A-Z]+.*', 'g' ),
		   rchild            = /^[\s>+~]/,
		   rcolonEnd         = /[\(,\[\s]/,
		   rcolonPass        = /[\[\s]/,
		   rnative           = new RegExp( '^:(link|visited||hover|only|first|before|after|lang|root|empty|target|enabled|disabled|checked|last|nth|nth-last)-(child|of-type|letter|line|child)', 'i' ),
		   ralter            = new RegExp( '^:(checkbox|file|image|password|radio|reset|submit)', 'i' ),
		   rattributeQuotes  = new RegExp( '=' + whitespace + '*([^\\]\'\"]*)' + whitespace + '*\\]', 'g' ),
		   rbuggyMatches     = /\:active/,
		   matchExpr         = {
			   'ID': new RegExp( '^#(' + characterEncoding + ')' ),
			   'CLASS': new RegExp( '^\\.(' + characterEncoding + ')' ),
			   'NAME': new RegExp( '^\\[name=[\'\"]?(' + characterEncoding + ')[\'\"]?\\]' ),
			   'TAG': new RegExp( '^(' + characterEncoding.replace( 'w', 'w*' ) + ')' ),
			   'ATTR': new RegExp( '^' + attributes ),
			   'PSEUDO': new RegExp( '^' + pseudos ),
			   'POS': new RegExp( pos, 'i' ),
			   'CHILD': new RegExp( '^:(only|nth|first|last)-child(?:\\(' + whitespace + '*(even|odd|(([+-]|)(\\d*)n|)' + whitespace + '*(?:([+-]|)' + whitespace + '*(\\d+)|))' + whitespace + '*\\)|)', 'i' ),
			   'needsContext': new RegExp( '^' + whitespace + '*[>+~]|' + pos, 'i' )
		   };
